name: Test Workflow

on: 
  workflow_dispatch:
    inputs:
      secretName:
        description: 'Secret Name'     
        required: true
        default: 'warning'
      serviceName:
        description: 'CloudRun Service Name'
        required: true
      domainName:
        description: 'Domain Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      tag: $GITHUB_SHA
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Use logLevel and tags variables
          echo "Running tests with log level: ${{ inputs.secretName }}"
          echo "Using tags: ${{ inputs.serviceName }}"
          echo "Using tags: $tag"

