name: Test Workflow

on: 
  workflow_dispatch:
    inputs:
      secretName:
        type: choice
        description: 'Select Secret Name' 
        options: ["api-v3-prod", "api-v3-stg", "api-v3-stg-1"]

      serviceName:
        description: 'CloudRun Service Name'
        required: true
      domainName:
        description: 'Domain Name'
        required: true

jobs:
  build:
    runs-on: ubuntu-20.04

    env:
      tag: $GITHUB_SHA
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        run: |
          # Use logLevel and tags variables
          echo "Running tests with log level: ${{ inputs.secretName }}"
          echo "Using tags: ${{ inputs.serviceName }}"
          echo "Using tags: ${{ env.tag }}"
