name: Update STAGEVERSION

on:
  workflow_dispatch:  # Allows manual triggering of the workflow

permissions:
  contents: read
  actions: write

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
          

      - name: Update Image Version
        run: |
          echo $GITHUB_REPOSITORY
          python3 .github/workflows/versionScript/versioning-script.py $GITHUB_REPOSITORY
